AWSTemplateFormatVersion: "2010-09-09"
Description: "Auto Scaling Group + Launch Configuration para escalado de instancias de la app"

Parameters:
  LaunchTemplateId:
    Type: String
    Description: "Si usas LaunchTemplate (opcional). Deja vacío si usarás LaunchConfiguration."
    Default: ""
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0c55b159cbfafe1f0  # placeholder, ajustar por región o usar SSM param
  InstanceType:
    Type: String
    Default: t3.micro
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  SecurityGroupIds:
    Type: CommaDelimitedList
  SubnetIds:
    Type: CommaDelimitedList
  DesiredCapacity:
    Type: Number
    Default: 1
  MinSize:
    Type: Number
    Default: 1
  MaxSize:
    Type: Number
    Default: 3
  TargetGroupArn:
    Type: String

Resources:
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups: !Ref SecurityGroupIds
      IamInstanceProfile: !Ref "AWS::NoValue"

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchConfigurationName: !Ref LaunchConfig
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      TargetGroupARNs:
        - !Ref TargetGroupArn
      Tags:
        - Key: Name
          Value: app-asg
          PropagateAtLaunch: true

  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: SimpleScaling
      AdjustmentType: ChangeInCapacity
      Cooldown: 300
      ScalingAdjustment: 1

  ScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: SimpleScaling
      AdjustmentType: ChangeInCapacity
      Cooldown: 300
      ScalingAdjustment: -1

Outputs:
  AutoScalingGroupName:
    Value: !Ref AutoScalingGroup
    Export:
      Name: project-asg-name
